In [4]:
import sys
sys.path.insert(0,'../code')
import book_format
book_format.load_style('../code')

ModuleNotFoundError: No module named 'book_format'

In [3]:
import numpy as np

# Computational Statistics

## Distributions

In statistics a <span>**distribution**</span> is a set of values and
their corresponding probabilities.

For example, if you roll a six-sided die, the set of possible values is
the numbers 1 to 6, and the probability associated with each value is
1/6.

As another example, you might be interested in how many times each word
appears in common English usage. You could build a distribution that
includes each word and how many times it appears.

To represent a distribution, one could use two numpy arrays that
store values and their probabililties. These two arrays represent a 
<span>**probability mass function**</span> (PMF), which is a way to
represent a distribution mathematically.

To use numpy arrays the corresponding module has to be imported first:

In [5]:
import numpy as np

The following code builds two arrays to represent the distribution of
outcomes for a six-sided die as a PMF:

In [6]:
vals=np.array([1,2,3,4,5,6],dtype=float)
probs = np.full_like(vals,1/6,dtype=float)

print(vals)
print(probs)

[1. 2. 3. 4. 5. 6.]
[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]


The array `vals` contains the numbers on the sides of a six-sided die and the array `probs` contains the probabilities  associated with each value $1/6$.

Here’s another example that counts the number of times each word appears in a sequence:

In [7]:
word_list = np.array(['hi', 'the', 'bye', 'hi', 'football', 'sky'])
words_unique, words_counts = np.unique(word_list, return_counts=True)

print(words_unique)
print(words_counts)

['bye' 'football' 'hi' 'sky' 'the']
[1 1 2 1 1]


`np.unique` returns the unique values of an array and their counts.
The word counts are proportional to the probabilities to find each 
word in the word list. So after we count all the words, we can compute
probabilities by dividing through by the total number of words:

In [8]:
words_probs=words_counts / words_counts.sum()

print(words_unique)
print(words_probs)

['bye' 'football' 'hi' 'sky' 'the']
[0.16666667 0.16666667 0.33333333 0.16666667 0.16666667]


Once values and prbabilities are defined, one can get the probability associated with any value:

In [9]:
prob=words_probs[words_unique=='the']

print(prob)

[0.16666667]


And that would print the frequency of the word “the” as a fraction of
the words in the list.

To define a PMF two arrays with the values and their
probabilities are used, so the values in the PMF can be any hashable type. The
probabilities can be any numerical type, but they are usually
floating-point numbers (type `float`).

## The cookie problem

In the context of Bayes’s theorem, it is natural to use a Pmf to map
from each hypothesis to its probability. In the cookie problem, the
hypotheses are $B_1$ and $B_2$. In Python, I represent them with
strings:

In [10]:
prior = np.array([0.5,0.5])

This distribution, which contains the priors for each hypothesis, is
called (wait for it) the <span>**prior distribution**</span>.

To update the distribution based on new data (the vanilla cookie), we
multiply each prior by the corresponding likelihood. The likelihood of
drawing a vanilla cookie from Bowl 1 is 3/4. The likelihood for Bowl 2
is 1/2.

In [11]:
likelihood = np.array([30/40, 20/40])
product=prior*likelihood

`Mult` does what you would expect. It gets the probability for the given
hypothesis and multiplies by the given likelihood.

After this update, the distribution is no longer normalized, but because
these hypotheses are mutually exclusive and collectively exhaustive, we
can <span>**renormalize**</span>:

In [12]:
norm_constant = product.sum()
posterior = product / norm_constant

The result is a distribution that contains the posterior probability for
each hypothesis, which is called (wait now) the <span>**posterior
distribution**</span>.

Finally, we can get the posterior probability for Bowl 1:

In [13]:
print(f"The probability of the vanilla cookie came from the first bowl is {posterior[0]}")

The probability of the vanilla cookie came from the first bowl is 0.6


## The Bayesian framework

The Bayesian framework introduced in the original is not used here 
and all calculations are performed using numpy arrays.

## The Monty Hall problem

To solve the Monty Hall problem, the hypotheses and the prior are defined first:

In [14]:
hypos = np.array(['A','B','C'])
prior = np.array([1/3]*3)

Following the explanations from the previous chapter the likelihood after choosing the door B is defined as:

In [15]:
likelihood = np.array([0.5, 0, 1])

Finally, an update is performed and the posterior is calculated:

In [16]:
product = prior*likelihood
norm_constant = product.sum()
posterior = product / norm_constant
print(f"The probabilities of the car beeing behind doors {hypos} are {posterior}")

The probabilities of the car beeing behind doors ['A' 'B' 'C'] are [0.33333333 0.         0.66666667]


## Encapsulating the framework

The Bayesian framework introduced in the original is not used here and all calculations are performed using numpy arrays.

## The <span>M&M</span> problem

We can solve the <span>M&M</span> problem using the approach above.
Writing the `Likelihood` function is tricky, but everything else is
straightforward.

In [22]:
mix94_vals=np.array(['brown','yellow','red','green','orange','tan'])
mix94_counts=np.array([30,20,20,10,10,10],dtype=float)
mix94_probs=mix94_counts/mix94_counts.sum()

mix96_vals=np.array(['blue','green','orange','yellow','red','brown'])
mix96_counts=np.array([24,20,16,14,13,13],dtype=float)
mix96_probs=mix96_counts/mix96_counts.sum()

The array `hypos` represents the hypotheses. The first elment of the array `hypos` is that Bag 1 is from 1994 and Bag 2 from 1996. The second element of `hypos` is the other way around.

In [40]:
hypos=['Bag1_94_Bag2_96','Bag1_96_Bag2_94']

The prior for both of the hypotheses is 0.5.

In [41]:
prior = np.array([0.5,0.5])

The data that we have is an M&M drawn from the first bag was yellow and from the second bag was green. Using this data the likelihood of this even can be calculated for both  of the hypotheses.

In [42]:
likelihood=np.array([mix94_probs[np.argwhere(mix94_vals=='yellow')][0][0]*mix96_probs[np.argwhere(mix96_vals=='green')][0][0],
                     mix94_probs[np.argwhere(mix94_vals=='green')][0][0] *mix96_probs[np.argwhere(mix96_vals=='yellow')][0][0] ])

And finally the update:

In [43]:
product = prior*likelihood
norm_constant = product.sum()
posterior = product / norm_constant
print(f"The probabilities of the hypothses {hypos} are {posterior}")

The probabilities of the hypothses ['Bag1_94_Bag2_96', 'Bag1_96_Bag2_94'] are [0.74074074 0.25925926]


The posterior probability of `Bag1 94 Bag2 96` is approximately $20/27$, which is what
we got before.

## Discussion

This chapter presents a computational approach for performing the Bayesian 
update using `numpy`. Implementig all calculations manually is a tedious task
if you do some realworld analysis and in this case one should go for some 
existing frameworks for Bayesian analysis. However, performing the calculations 
from scratch can be helpful for a better understanding of the analysis procedure.

Most of the examples in the following chapters have the same pattern;
for each problem we define a hypotheses set and the corresponding priors. 
Then we calculate the likelihood given some data and finally perform an update
to get the posterior.

## Exercises

In Section [framework] I said that the solution to the cookie problem
generalizes to the case where we draw multiple cookies with replacement.

But in the more likely scenario where we eat the cookies we draw, the
likelihood of each draw depends on the previous draws.

Modify the solution in this chapter to handle selection without
replacement. Hint: add instance variables to <span>Cookie</span> to
represent the hypothetical state of the bowls, and modify
<span>Likelihood</span> accordingly. You might want to define a
<span>Bowl</span> object.